#!/bin/sh
if [ -z "$AGORA_SCHOLAR_VERSION" ]; then    
    /usr/lib/agora/.env/bin/pip install --upgrade Agora-Scholar
else
	/usr/lib/agora/.env/bin/pip install --upgrade Agora-Scholar==$AGORA_SCHOLAR_VERSION
fi

/usr/lib/agora/.env/bin/scholar &